### ISSUE TITLE
TypeError: Note must be text (unicode)

### ISSUE THREAD

**Issue by hlopezvg** [morepath/morepath_rest_dump_load#1] opened 2016-12-26 20:47 UTC
Hi,

I just followed all the steps you had on the readme, but once I hit http://localhost:5000 I got the following error:

  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/morepath_sqlalchemy/env/local/lib/python2.7/site-packages/morepath/app.py", line 138, in __call__
    response = self.publish(request)
  File "/morepath_sqlalchemy/env/local/lib/python2.7/site-packages/morepath/core.py", line 217, in poisoned_host_header_protection_tween
    return handler(request)
  File "/morepath_sqlalchemy/env/local/lib/python2.7/site-packages/more/transaction/main.py", line 64, in transaction_tween
    t.note(request.path)
  File "/morepath_sqlalchemy/env/local/lib/python2.7/site-packages/transaction/_transaction.py", line 537, in note
    raise TypeError("Note must be text (unicode)")
TypeError: Note must be text (unicode)

Thanks for the help

**Comment by jugmac00** [comment] 2020-10-02 13:30
Took a while to answer :-), but currently I cannot reproduce any errors. The example on the readme works like a charm.

Also, support for Python 2.7 has been dropped - closing this issue.

Feel free to create a new one, if you encounter any problems.

**Closed by jugmac00** 2020-10-02 13:30 UTC
